import type { ActiveOrder, DashboardData, OrderLine } from "./types";

const THUMBS: OrderLine[] = [
  { id: "t-paint", name: "Asian Paints Interior Emulsion 10L", image: "/partner/paints.png", qty: 2 },
  { id: "t-pipe", name: "Astral PVC Pipe 20 mm", image: "/partner/pipes.png", qty: 4 },
  { id: "t-led", name: "EcoLink Surface LED 15W", image: "/partner/led.png", qty: 3 },
  { id: "t-switch", name: "Anchor Penta 6A Switch", image: "/partner/electricals.png", qty: 2 },
  { id: "t-tool", name: "Bosch 10mm Impact Drill", image: "/partner/tools.png", qty: 1 },
];

function withItems(order: Omit<ActiveOrder, "items">, count: number): ActiveOrder {
  return { ...order, items: THUMBS.slice(0, Math.min(4, count)) };
}

export const MOCK_DASHBOARD: DashboardData = {
  store: {
    id: "store-sharma",
    name: "Sharma Hardware",
    storeId: "HW-1024",
    status: "open",
    hours: "Mon – Sat  9:00 AM – 8:00 PM",
  },
  overview: {
    ordersToday: 18,
    ordersTodayChange: 12,
    ordersOnline: 12,
    ordersOffline: 6,
    salesToday: 12450,
    salesTodayChange: 8,
    salesOnline: 8450,
    salesOffline: 4000,
    pendingOrders: 4,
    itemsToPack: 7,
  },
  attentionItems: [
    {
      id: "att-new",
      kind: "new_orders",
      title: "New Orders",
      description: "Waiting for confirmation",
      count: 4,
      href: "/partner/orders",
      actionLabel: "View Orders",
    },
    {
      id: "att-low",
      kind: "low_stock",
      title: "Low Stock",
      description: "Running low",
      count: 12,
      href: "/partner/inventory",
      actionLabel: "Review Stock",
    },
    {
      id: "att-out",
      kind: "out_of_stock",
      title: "Out of Stock",
      description: "Currently unavailable",
      count: 5,
      href: "/partner/inventory",
      actionLabel: "Update Inventory",
    },
  ],
  activeOrders: [
    withItems(
      {
        id: "ord-2874",
        displayId: "KW-2874",
        time: "10:42 AM",
        itemCount: 16,
        area: "Niti Vihar, Block I, 35, 70 Feet Road",
        value: 4250,
        status: "NEW",
      },
      4,
    ),
    withItems(
      {
        id: "ord-2841",
        displayId: "KW-2841",
        time: "10:28 AM",
        itemCount: 3,
        area: "Prem Nagar II, Lane 4, House 12",
        value: 1250,
        status: "NEW",
      },
      3,
    ),
    withItems(
      {
        id: "ord-2840",
        displayId: "KW-2840",
        time: "10:15 AM",
        itemCount: 1,
        area: "Shankar Vihar, Shop 8, Main Market",
        value: 430,
        status: "NEW",
      },
      1,
    ),
    withItems(
      {
        id: "ord-2839",
        displayId: "KW-2839",
        time: "10:08 AM",
        itemCount: 2,
        area: "Prem Nagar II, Block C, 19",
        value: 640,
        status: "NEW",
      },
      2,
    ),
    withItems(
      {
        id: "ord-2838",
        displayId: "KW-2838",
        time: "10:05 AM",
        itemCount: 5,
        area: "Niti Vihar, Block I, 35, 70 Feet Road",
        value: 2450,
        status: "PREPARING",
        readyInSec: 18 * 60 + 32,
        prepTotalSec: 20 * 60,
      },
      4,
    ),
    withItems(
      {
        id: "ord-2836",
        displayId: "KW-2836",
        time: "9:48 AM",
        itemCount: 2,
        area: "Shankar Vihar, Shop 8, Main Market",
        value: 890,
        status: "PREPARING",
        readyInSec: 8 * 60 + 15,
        prepTotalSec: 15 * 60,
      },
      2,
    ),
    withItems(
      {
        id: "ord-2835",
        displayId: "KW-2835",
        time: "9:20 AM",
        itemCount: 2,
        area: "Niti Vihar, Lane 2, House 41",
        value: 850,
        status: "READY",
      },
      2,
    ),
    withItems(
      {
        id: "ord-2832",
        displayId: "KW-2832",
        time: "9:05 AM",
        itemCount: 4,
        area: "Prem Nagar II, Block A, 7",
        value: 1680,
        status: "READY",
      },
      4,
    ),
  ],
  inventoryAlerts: [
    {
      id: "inv-paint",
      name: "Asian Paints Interior Emulsion",
      sku: "AP-IE10",
      quantity: 4,
      unit: "units",
      status: "low",
      threshold: 10,
      suggestedReorder: 12,
      image: "/partner/paints.png",
    },
    {
      id: "inv-elbow",
      name: "20mm PVC Elbow",
      sku: "PVC20E",
      quantity: 0,
      unit: "units",
      status: "out",
      suggestedReorder: 50,
      image: "/partner/pipes.png",
    },
    {
      id: "inv-switch",
      name: "Anchor Penta 6A Bed Switch",
      sku: "2527",
      quantity: 0,
      unit: "pieces",
      status: "out",
      suggestedReorder: 24,
      image: "/partner/electricals.png",
    },
    {
      id: "inv-wire",
      name: "Polycab 2.5 sq.mm Wire",
      sku: "PC25",
      quantity: 4,
      unit: "units",
      status: "low",
      threshold: 5,
      suggestedReorder: 20,
      image: "/partner/led.png",
    },
  ],
  recentActivity: [
    {
      id: "act-1",
      time: "10:42 AM",
      type: "order_accepted",
      description: "Order #KW-2874 received",
      ref: "KW-2874",
    },
    {
      id: "act-2",
      time: "10:35 AM",
      type: "stock_added",
      description: "20 units of Polycab 2.5 sq.mm Wire added to inventory",
      ref: "PC25",
    },
    {
      id: "act-3",
      time: "10:12 AM",
      type: "order_completed",
      description: "Order #KW-2839 completed",
      ref: "KW-2839",
    },
  ],
  notifications: [
    {
      id: "n1",
      kind: "order",
      title: "New order received",
      body: "Order #KW-2874 · Niti Vihar · ₹4,250",
      time: "10:42 AM",
      unread: true,
    },
    {
      id: "n2",
      kind: "stock",
      title: "Low-stock alert",
      body: "Asian Paints Interior Emulsion is down to 4 units",
      time: "10:18 AM",
      unread: true,
    },
    {
      id: "n3",
      kind: "settlement",
      title: "Settlement processed",
      body: "₹8,450 credited for yesterday’s orders",
      time: "9:50 AM",
      unread: true,
    },
    {
      id: "n4",
      kind: "product",
      title: "Product approval update",
      body: "Bosch 10mm Masonry Bit is now available to stock",
      time: "9:10 AM",
      unread: true,
    },
  ],
  insight: {
    id: "insight-offline",
    title: "Keep inventory updated",
    body: "Record offline sales so stock and insights stay accurate.",
    href: "/partner/sell",
    actionLabel: "Learn more",
  },
};
